import { db } from '@/db';
import { bets } from '@/db/schema';

async function main() {
    const sampleBets = [
        // Market 1: Bitcoin Price - Popular market with many bets
        {
            marketId: 1,
            userWallet: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
            amount: 15.5,
            prediction: 'yes',
            priceAtBet: 0.68,
            potentialPayout: 22.79,
            actualPayout: 0,
            platformFee: 0.31,
            transactionSignature: '5J8N99VFjGKvBvPLvXqjLqKqZgXfJxvxKxvxKxvxKxvxKxvxKxvxKxvxKxvxKxvxKxvxKxvxKxvx',
            timestamp: new Date('2024-12-15T10:30:00').toISOString(),
            isSettled: false,
        },
        {
            marketId: 1,
            userWallet: '9WzDXwBbmkg8ZTbNMqUxvQRAb9jLmzVn',
            amount: 50.0,
            prediction: 'yes',
            priceAtBet: 0.67,
            potentialPayout: 74.63,
            actualPayout: 0,
            platformFee: 1.0,
            transactionSignature: '3kPQR7vYzN8WxLmKpQrStUvWxYzAbCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKlMnOpQrStUvW',
            timestamp: new Date('2024-12-16T14:20:00').toISOString(),
            isSettled: false,
        },
        {
            marketId: 1,
            userWallet: 'HN7cABqLq46Es1jh9dT3SJ96pqGC1T3p',
            amount: 8.25,
            prediction: 'no',
            priceAtBet: 0.33,
            potentialPayout: 25.0,
            actualPayout: 0,
            platformFee: 0.17,
            transactionSignature: '2mNoBpCrDsEtFuGvHwIxJyKzLaMbNcOdPeQfRgShTiUjVkWlXmYnZoApBqCrDsEtFuGvHwIxJyKz',
            timestamp: new Date('2024-12-18T09:15:00').toISOString(),
            isSettled: false,
        },
        {
            marketId: 1,
            userWallet: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
            amount: 25.0,
            prediction: 'yes',
            priceAtBet: 0.65,
            potentialPayout: 38.46,
            actualPayout: 0,
            platformFee: 0.5,
            transactionSignature: '4nOpQrStUvWxYzAbCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIj',
            timestamp: new Date('2024-12-19T16:45:00').toISOString(),
            isSettled: false,
        },

        // Market 2: Ethereum ETF - Another popular market
        {
            marketId: 2,
            userWallet: 'HN7cABqLq46Es1jh9dT3SJ96pqGC1T3p',
            amount: 12.0,
            prediction: 'yes',
            priceAtBet: 0.72,
            potentialPayout: 16.67,
            actualPayout: 0,
            platformFee: 0.24,
            transactionSignature: '6pQrStUvWxYzAbCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKl',
            timestamp: new Date('2024-12-10T11:30:00').toISOString(),
            isSettled: false,
        },
        {
            marketId: 2,
            userWallet: '9WzDXwBbmkg8ZTbNMqUxvQRAb9jLmzVn',
            amount: 5.5,
            prediction: 'yes',
            priceAtBet: 0.71,
            potentialPayout: 7.75,
            actualPayout: 0,
            platformFee: 0.11,
            transactionSignature: '7qRsStUvWxYzAbCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKl',
            timestamp: new Date('2024-12-12T13:20:00').toISOString(),
            isSettled: false,
        },
        {
            marketId: 2,
            userWallet: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
            amount: 30.0,
            prediction: 'no',
            priceAtBet: 0.28,
            potentialPayout: 107.14,
            actualPayout: 0,
            platformFee: 0.6,
            transactionSignature: '8rStTuUvWxYzAbCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKl',
            timestamp: new Date('2024-12-14T15:10:00').toISOString(),
            isSettled: false,
        },

        // Market 3: US Elections - High volume market
        {
            marketId: 3,
            userWallet: 'HN7cABqLq46Es1jh9dT3SJ96pqGC1T3p',
            amount: 100.0,
            prediction: 'yes',
            priceAtBet: 0.52,
            potentialPayout: 192.31,
            actualPayout: 192.31,
            platformFee: 2.0,
            transactionSignature: '9sStTuUvWxYzAbCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKl',
            timestamp: new Date('2024-11-01T08:00:00').toISOString(),
            isSettled: true,
        },
        {
            marketId: 3,
            userWallet: '9WzDXwBbmkg8ZTbNMqUxvQRAb9jLmzVn',
            amount: 75.0,
            prediction: 'yes',
            priceAtBet: 0.54,
            potentialPayout: 138.89,
            actualPayout: 138.89,
            platformFee: 1.5,
            transactionSignature: '1tTuUvVwWxYzAbCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKl',
            timestamp: new Date('2024-11-02T12:30:00').toISOString(),
            isSettled: true,
        },
        {
            marketId: 3,
            userWallet: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
            amount: 45.0,
            prediction: 'no',
            priceAtBet: 0.48,
            potentialPayout: 93.75,
            actualPayout: 0,
            platformFee: 0.9,
            transactionSignature: '2uUvVwWxXyYzAbCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKl',
            timestamp: new Date('2024-11-03T09:45:00').toISOString(),
            isSettled: true,
        },

        // Market 4: Solana DeFi TVL
        {
            marketId: 4,
            userWallet: 'HN7cABqLq46Es1jh9dT3SJ96pqGC1T3p',
            amount: 20.0,
            prediction: 'yes',
            priceAtBet: 0.58,
            potentialPayout: 34.48,
            actualPayout: 0,
            platformFee: 0.4,
            transactionSignature: '3vVwWxXyYzZaAbCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKl',
            timestamp: new Date('2024-12-17T10:00:00').toISOString(),
            isSettled: false,
        },
        {
            marketId: 4,
            userWallet: '9WzDXwBbmkg8ZTbNMqUxvQRAb9jLmzVn',
            amount: 10.5,
            prediction: 'yes',
            priceAtBet: 0.59,
            potentialPayout: 17.8,
            actualPayout: 0,
            platformFee: 0.21,
            transactionSignature: '4wWxXyYzZaAbBcCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKl',
            timestamp: new Date('2024-12-18T14:30:00').toISOString(),
            isSettled: false,
        },

        // Market 5: OpenAI CEO
        {
            marketId: 5,
            userWallet: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
            amount: 3.5,
            prediction: 'no',
            priceAtBet: 0.78,
            potentialPayout: 4.49,
            actualPayout: 0,
            platformFee: 0.07,
            transactionSignature: '5xXyYzZaAbBcCdDeEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKl',
            timestamp: new Date('2024-12-05T11:15:00').toISOString(),
            isSettled: false,
        },
        {
            marketId: 5,
            userWallet: 'HN7cABqLq46Es1jh9dT3SJ96pqGC1T3p',
            amount: 7.0,
            prediction: 'no',
            priceAtBet: 0.76,
            potentialPayout: 9.21,
            actualPayout: 0,
            platformFee: 0.14,
            transactionSignature: '6yYzZaAbBcCdDeEfFgGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKl',
            timestamp: new Date('2024-12-08T16:20:00').toISOString(),
            isSettled: false,
        },

        // Market 6: Tesla Stock Price
        {
            marketId: 6,
            userWallet: '9WzDXwBbmkg8ZTbNMqUxvQRAb9jLmzVn',
            amount: 18.0,
            prediction: 'yes',
            priceAtBet: 0.61,
            potentialPayout: 29.51,
            actualPayout: 0,
            platformFee: 0.36,
            transactionSignature: '7zZaAbBcCdDeEfFgGhHiIjKlMnOpQrStUvWxYzAbCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKl',
            timestamp: new Date('2024-12-13T09:30:00').toISOString(),
            isSettled: false,
        },
        {
            marketId: 6,
            userWallet: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
            amount: 42.0,
            prediction: 'yes',
            priceAtBet: 0.62,
            potentialPayout: 67.74,
            actualPayout: 0,
            platformFee: 0.84,
            transactionSignature: '8aAbBcCdDeEfFgGhHiIjJkKlMnOpQrStUvWxYzAbCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKl',
            timestamp: new Date('2024-12-15T13:45:00').toISOString(),
            isSettled: false,
        },

        // Market 7: Champions League Winner
        {
            marketId: 7,
            userWallet: 'HN7cABqLq46Es1jh9dT3SJ96pqGC1T3p',
            amount: 6.0,
            prediction: 'yes',
            priceAtBet: 0.48,
            potentialPayout: 12.5,
            actualPayout: 0,
            platformFee: 0.12,
            transactionSignature: '9bBcCdDeEfFgGhHiIjJkKlLmMnOpQrStUvWxYzAbCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKl',
            timestamp: new Date('2024-12-11T18:00:00').toISOString(),
            isSettled: false,
        },
        {
            marketId: 7,
            userWallet: '9WzDXwBbmkg8ZTbNMqUxvQRAb9jLmzVn',
            amount: 14.5,
            prediction: 'yes',
            priceAtBet: 0.49,
            potentialPayout: 29.59,
            actualPayout: 0,
            platformFee: 0.29,
            transactionSignature: '1cCdDeEfFgGhHiIjJkKlLmMnNoOpQrStUvWxYzAbCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKl',
            timestamp: new Date('2024-12-16T20:30:00').toISOString(),
            isSettled: false,
        },

        // Market 8: NFT Market Recovery
        {
            marketId: 8,
            userWallet: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
            amount: 22.0,
            prediction: 'no',
            priceAtBet: 0.69,
            potentialPayout: 31.88,
            actualPayout: 0,
            platformFee: 0.44,
            transactionSignature: '2dDeEfFgGhHiIjJkKlLmMnNoOpPqQrStUvWxYzAbCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKl',
            timestamp: new Date('2024-12-09T10:45:00').toISOString(),
            isSettled: false,
        },
        {
            marketId: 8,
            userWallet: 'HN7cABqLq46Es1jh9dT3SJ96pqGC1T3p',
            amount: 9.0,
            prediction: 'yes',
            priceAtBet: 0.31,
            potentialPayout: 29.03,
            actualPayout: 0,
            platformFee: 0.18,
            transactionSignature: '3eEfFgGhHiIjJkKlLmMnNoOpPqQrRsStUvWxYzAbCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKl',
            timestamp: new Date('2024-12-12T15:20:00').toISOString(),
            isSettled: false,
        },

        // Market 9: Fed Interest Rate
        {
            marketId: 9,
            userWallet: '9WzDXwBbmkg8ZTbNMqUxvQRAb9jLmzVn',
            amount: 35.0,
            prediction: 'yes',
            priceAtBet: 0.74,
            potentialPayout: 47.3,
            actualPayout: 47.3,
            platformFee: 0.7,
            transactionSignature: '4fFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvWxYzAbCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKl',
            timestamp: new Date('2024-11-15T14:00:00').toISOString(),
            isSettled: true,
        },
        {
            marketId: 9,
            userWallet: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
            amount: 28.0,
            prediction: 'yes',
            priceAtBet: 0.73,
            potentialPayout: 38.36,
            actualPayout: 38.36,
            platformFee: 0.56,
            transactionSignature: '5gGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxYzAbCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKl',
            timestamp: new Date('2024-11-16T11:30:00').toISOString(),
            isSettled: true,
        },

        // Market 10: Dogecoin Price
        {
            marketId: 10,
            userWallet: 'HN7cABqLq46Es1jh9dT3SJ96pqGC1T3p',
            amount: 11.0,
            prediction: 'yes',
            priceAtBet: 0.55,
            potentialPayout: 20.0,
            actualPayout: 0,
            platformFee: 0.22,
            transactionSignature: '6hHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzAbCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKl',
            timestamp: new Date('2024-12-14T12:15:00').toISOString(),
            isSettled: false,
        },
        {
            marketId: 10,
            userWallet: '9WzDXwBbmkg8ZTbNMqUxvQRAb9jLmzVn',
            amount: 5.0,
            prediction: 'no',
            priceAtBet: 0.45,
            potentialPayout: 11.11,
            actualPayout: 0,
            platformFee: 0.1,
            transactionSignature: '7iIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZaAbCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKl',
            timestamp: new Date('2024-12-17T16:40:00').toISOString(),
            isSettled: false,
        },

        // Market 11: Apple Vision Pro Sales
        {
            marketId: 11,
            userWallet: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
            amount: 16.0,
            prediction: 'yes',
            priceAtBet: 0.42,
            potentialPayout: 38.1,
            actualPayout: 0,
            platformFee: 0.32,
            transactionSignature: '8jJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZaAbBcCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKl',
            timestamp: new Date('2024-12-10T13:25:00').toISOString(),
            isSettled: false,
        },
        {
            marketId: 11,
            userWallet: 'HN7cABqLq46Es1jh9dT3SJ96pqGC1T3p',
            amount: 8.5,
            prediction: 'no',
            priceAtBet: 0.58,
            potentialPayout: 14.66,
            actualPayout: 0,
            platformFee: 0.17,
            transactionSignature: '9kKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZaAbBcCdDeEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKl',
            timestamp: new Date('2024-12-13T17:50:00').toISOString(),
            isSettled: false,
        },

        // Market 12: Inflation Rate
        {
            marketId: 12,
            userWallet: '9WzDXwBbmkg8ZTbNMqUxvQRAb9jLmzVn',
            amount: 24.0,
            prediction: 'no',
            priceAtBet: 0.64,
            potentialPayout: 37.5,
            actualPayout: 0,
            platformFee: 0.48,
            transactionSignature: '1lLmMnNoOpPqQrRsStTuUvVwWxXyYzZaAbBcCdDeEfFgGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKl',
            timestamp: new Date('2024-12-11T10:30:00').toISOString(),
            isSettled: false,
        },
        {
            marketId: 12,
            userWallet: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
            amount: 13.5,
            prediction: 'yes',
            priceAtBet: 0.36,
            potentialPayout: 37.5,
            actualPayout: 0,
            platformFee: 0.27,
            transactionSignature: '2mMnNoOpPqQrRsStTuUvVwWxXyYzZaAbBcCdDeEfFgGhHiIjKlMnOpQrStUvWxYzAbCdEfGhIjKl',
            timestamp: new Date('2024-12-15T14:45:00').toISOString(),
            isSettled: false,
        },

        // Market 13: Grand Theft Auto 6 Release
        {
            marketId: 13,
            userWallet: 'HN7cABqLq46Es1jh9dT3SJ96pqGC1T3p',
            amount: 19.0,
            prediction: 'yes',
            priceAtBet: 0.81,
            potentialPayout: 23.46,
            actualPayout: 0,
            platformFee: 0.38,
            transactionSignature: '3nNoOpPqQrRsStTuUvVwWxXyYzZaAbBcCdDeEfFgGhHiIjJkKlMnOpQrStUvWxYzAbCdEfGhIjKl',
            timestamp: new Date('2024-12-08T11:00:00').toISOString(),
            isSettled: false,
        },
        {
            marketId: 13,
            userWallet: '9WzDXwBbmkg8ZTbNMqUxvQRAb9jLmzVn',
            amount: 32.0,
            prediction: 'yes',
            priceAtBet: 0.82,
            potentialPayout: 39.02,
            actualPayout: 0,
            platformFee: 0.64,
            transactionSignature: '4oOpPqQrRsStTuUvVwWxXyYzZaAbBcCdDeEfFgGhHiIjJkKlLmMnOpQrStUvWxYzAbCdEfGhIjKl',
            timestamp: new Date('2024-12-12T15:30:00').toISOString(),
            isSettled: false,
        },

        // Market 14: Global Temperature Record
        {
            marketId: 14,
            userWallet: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
            amount: 4.5,
            prediction: 'yes',
            priceAtBet: 0.63,
            potentialPayout: 7.14,
            actualPayout: 0,
            platformFee: 0.09,
            transactionSignature: '5pPqQrRsStTuUvVwWxXyYzZaAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpQrStUvWxYzAbCdEfGhIjKl',
            timestamp: new Date('2024-12-06T09:20:00').toISOString(),
            isSettled: false,
        },
        {
            marketId: 14,
            userWallet: 'HN7cABqLq46Es1jh9dT3SJ96pqGC1T3p',
            amount: 11.5,
            prediction: 'yes',
            priceAtBet: 0.65,
            potentialPayout: 17.69,
            actualPayout: 0,
            platformFee: 0.23,
            transactionSignature: '6qQrRsStTuUvVwWxXyYzZaAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrStUvWxYzAbCdEfGhIjKl',
            timestamp: new Date('2024-12-14T13:10:00').toISOString(),
            isSettled: false,
        },

        // Market 15: SpaceX Mars Mission
        {
            marketId: 15,
            userWallet: '9WzDXwBbmkg8ZTbNMqUxvQRAb9jLmzVn',
            amount: 55.0,
            prediction: 'no',
            priceAtBet: 0.88,
            potentialPayout: 62.5,
            actualPayout: 0,
            platformFee: 1.1,
            transactionSignature: '7rRsStTuUvVwWxXyYzZaAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrStUvWxYzAbCdEfGhIjKl',
            timestamp: new Date('2024-12-07T16:00:00').toISOString(),
            isSettled: false,
        },
        {
            marketId: 15,
            userWallet: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
            amount: 27.0,
            prediction: 'no',
            priceAtBet: 0.87,
            potentialPayout: 31.03,
            actualPayout: 0,
            platformFee: 0.54,
            transactionSignature: '8sStTuUvVwWxXyYzZaAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStUvWxYzAbCdEfGhIjKl',
            timestamp: new Date('2024-12-11T12:45:00').toISOString(),
            isSettled: false,
        },

        // Additional bets to reach 50 - distributed across markets
        {
            marketId: 1,
            userWallet: 'HN7cABqLq46Es1jh9dT3SJ96pqGC1T3p',
            amount: 2.5,
            prediction: 'yes',
            priceAtBet: 0.66,
            potentialPayout: 3.79,
            actualPayout: 0,
            platformFee: 0.05,
            transactionSignature: '9tTuUvVwWxXyYzZaAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvWxYzAbCdEfGhIjKl',
            timestamp: new Date('2024-12-19T18:30:00').toISOString(),
            isSettled: false,
        },
        {
            marketId: 2,
            userWallet: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
            amount: 38.0,
            prediction: 'yes',
            priceAtBet: 0.7,
            potentialPayout: 54.29,
            actualPayout: 0,
            platformFee: 0.76,
            transactionSignature: '1uUvVwWxXyYzZaAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxYzAbCdEfGhIjKl',
            timestamp: new Date('2024-12-18T11:20:00').toISOString(),
            isSettled: false,
        },
        {
            marketId: 4,
            userWallet: '9WzDXwBbmkg8ZTbNMqUxvQRAb9jLmzVn',
            amount: 7.5,
            prediction: 'no',
            priceAtBet: 0.42,
            potentialPayout: 17.86,
            actualPayout: 0,
            platformFee: 0.15,
            transactionSignature: '2vVwWxXyYzZaAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzAbCdEfGhIjKl',
            timestamp: new Date('2024-12-19T09:45:00').toISOString(),
            isSettled: false,
        },
        {
            marketId: 6,
            userWallet: 'HN7cABqLq46Es1jh9dT3SJ96pqGC1T3p',
            amount: 15.0,
            prediction: 'no',
            priceAtBet: 0.39,
            potentialPayout: 38.46,
            actualPayout: 0,
            platformFee: 0.3,
            transactionSignature: '3wWxXyYzZaAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZaAbCdEfGhIjKl',
            timestamp: new Date('2024-12-16T14:00:00').toISOString(),
            isSettled: false,
        },
        {
            marketId: 7,
            userWallet: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
            amount: 9.5,
            prediction: 'no',
            priceAtBet: 0.51,
            potentialPayout: 18.63,
            actualPayout: 0,
            platformFee: 0.19,
            transactionSignature: '4xXyYzZaAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZaAbBcCdEfGhIjKl',
            timestamp: new Date('2024-12-17T19:15:00').toISOString(),
            isSettled: false,
        },
        {
            marketId: 10,
            userWallet: '9WzDXwBbmkg8ZTbNMqUxvQRAb9jLmzVn',
            amount: 21.0,
            prediction: 'yes',
            priceAtBet: 0.56,
            potentialPayout: 37.5,
            actualPayout: 0,
            platformFee: 0.42,
            transactionSignature: '5yYzZaAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZaAbBcCdDeEfGhIjKl',
            timestamp: new Date('2024-12-18T15:20:00').toISOString(),
            isSettled: false,
        },
        {
            marketId: 3,
            userWallet: 'HN7cABqLq46Es1jh9dT3SJ96pqGC1T3p',
            amount: 62.0,
            prediction: 'yes',
            priceAtBet: 0.53,
            potentialPayout: 116.98,
            actualPayout: 116.98,
            platformFee: 1.24,
            transactionSignature: '6zZaAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZaAbBcCdDeEfFgGhIjKl',
            timestamp: new Date('2024-11-04T10:00:00').toISOString(),
            isSettled: true,
        },
        {
            marketId: 9,
            userWallet: '9WzDXwBbmkg8ZTbNMqUxvQRAb9jLmzVn',
            amount: 41.0,
            prediction: 'no',
            priceAtBet: 0.26,
            potentialPayout: 157.69,
            actualPayout: 0,
            platformFee: 0.82,
            transactionSignature: '7aAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZaAbBcCdDeEfFgGhHiIjKl',
            timestamp: new Date('2024-11-17T13:30:00').toISOString(),
            isSettled: true,
        },
        {
            marketId: 1,
            userWallet: '9WzDXwBbmkg8ZTbNMqUxvQRAb9jLmzVn',
            amount: 12.5,
            prediction: 'yes',
            priceAtBet: 0.69,
            potentialPayout: 18.12,
            actualPayout: 0,
            platformFee: 0.25,
            transactionSignature: '8bBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZaAbBcCdDeEfFgGhHiIjJkKl',
            timestamp: new Date('2024-12-20T08:15:00').toISOString(),
            isSettled: false,
        },
        {
            marketId: 11,
            userWallet: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
            amount: 5.8,
            prediction: 'yes',
            priceAtBet: 0.43,
            potentialPayout: 13.49,
            actualPayout: 0,
            platformFee: 0.12,
            transactionSignature: '9cCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZaAbBcCdDeEfFgGhHiIjJkKlLm',
            timestamp: new Date('2024-12-16T11:40:00').toISOString(),
            isSettled: false,
        },
        {
            marketId: 12,
            userWallet: 'HN7cABqLq46Es1jh9dT3SJ96pqGC1T3p',
            amount: 29.0,
            prediction: 'no',
            priceAtBet: 0.64,
            potentialPayout: 45.31,
            actualPayout: 0,
            platformFee: 0.58,
            transactionSignature: '1dDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZaAbBcCdDeEfFgGhHiIjJkKlLmMn',
            timestamp: new Date('2024-12-17T14:25:00').toISOString(),
            isSettled: false,
        },
        {
            marketId: 13,
            userWallet: '9WzDXwBbmkg8ZTbNMqUxvQRAb9jLmzVn',
            amount: 16.5,
            prediction: 'yes',
            priceAtBet: 0.8,
            potentialPayout: 20.63,
            actualPayout: 0,
            platformFee: 0.33,
            transactionSignature: '2eEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZaAbBcCdDeEfFgGhHiIjJkKlLmMnNo',
            timestamp: new Date('2024-12-15T16:50:00').toISOString(),
            isSettled: false,
        },
        {
            marketId: 14,
            userWallet: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
            amount: 8.0,
            prediction: 'no',
            priceAtBet: 0.37,
            potentialPayout: 21.62,
            actualPayout: 0,
            platformFee: 0.16,
            transactionSignature: '3fFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZaAbBcCdDeEfFgGhHiIjJkKlLmMnNoOp',
            timestamp: new Date('2024-12-19T12:30:00').toISOString(),
            isSettled: false,
        },
        {
            marketId: 2,
            userWallet: 'HN7cABqLq46Es1jh9dT3SJ96pqGC1T3p',
            amount: 44.0,
            prediction: 'yes',
            priceAtBet: 0.72,
            potentialPayout: 61.11,
            actualPayout: 0,
            platformFee: 0.88,
            transactionSignature: '4gGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZaAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPq',
            timestamp: new Date('2024-12-19T17:10:00').toISOString(),
            isSettled: false,
        },
        {
            marketId: 8,
            userWallet: '9WzDXwBbmkg8ZTbNMqUxvQRAb9jLmzVn',
            amount: 17.5,
            prediction: 'yes',
            priceAtBet: 0.32,
            potentialPayout: 54.69,
            actualPayout: 0,
            platformFee: 0.35,
            transactionSignature: '5hHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZaAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQr',
            timestamp: new Date('2024-12-18T13:55:00').toISOString(),
            isSettled: false,
        },
        {
            marketId: 3,
            userWallet: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
            amount: 88.0,
            prediction: 'yes',
            priceAtBet: 0.51,
            potentialPayout: 172.55,
            actualPayout: 172.55,
            platformFee: 1.76,
            transactionSignature: '6iIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZaAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRs',
            timestamp: new Date('2024-11-05T15:20:00').toISOString(),
            isSettled: true,
        },
        {
            marketId: 5,
            userWallet: 'HN7cABqLq46Es1jh9dT3SJ96pqGC1T3p',
            amount: 13.2,
            prediction: 'no',
            priceAtBet: 0.77,
            potentialPayout: 17.14,
            actualPayout: 0,
            platformFee: 0.26,
            transactionSignature: '7jJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZaAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsSt',
            timestamp: new Date('2024-12-11T09:05:00').toISOString(),
            isSettled: false,
        },
        {
            marketId: 6,
            userWallet: '9WzDXwBbmkg8ZTbNMqUxvQRAb9jLmzVn',
            amount: 26.0,
            prediction: 'yes',
            priceAtBet: 0.63,
            potentialPayout: 41.27,
            actualPayout: 0,
            platformFee: 0.52,
            transactionSignature: '8kKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZaAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTu',
            timestamp: new Date('2024-12-19T10:30:00').toISOString(),
            isSettled: false,
        },
        {
            marketId: 10,
            userWallet: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
            amount: 33.5,
            prediction: 'yes',
            priceAtBet: 0.54,
            potentialPayout: 62.04,
            actualPayout: 0,
            platformFee: 0.67,
            transactionSignature: '9lLmMnNoOpPqQrRsStTuUvVwWxXyYzZaAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUv',
            timestamp: new Date('2024-12-20T11:45:00').toISOString(),
            isSettled: false,
        },
        {
            marketId: 15,
            userWallet: 'HN7cABqLq46Es1jh9dT3SJ96pqGC1T3p',
            amount: 14.0,
            prediction: 'no',
            priceAtBet: 0.86,
            potentialPayout: 16.28,
            actualPayout: 0,
            platformFee: 0.28,
            transactionSignature: '1mMnNoOpPqQrRsStTuUvVwWxXyYzZaAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVw',
            timestamp: new Date('2024-12-13T14:35:00').toISOString(),
            isSettled: false,
        },
    ];

    await db.insert(bets).values(sampleBets);
    
    console.log('✅ Bets seeder completed successfully - 50 realistic bets created');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});